package io.epavlov.ktelemetry.backend.repository

import kotlinx.serialization.Serializable

@Suppress("PropertyName")
@Serializable
data class FlatTelemetryEvent(
    val event_time: Long,
    val event_time_zone_id: String? = null,
    val event_utc_offset_minutes: Int? = null,
    val event_type: String,
    val event_name: String,
    val level: String,
    val app_id: String,
    val app_version: String? = null,
    val app_name: String? = null,
    val app_build_number: String? = null,
    val app_environment: String? = null,
    val user_id: String,
    val anonymous_id: String,
    val user_name: String? = null,
    val user_email: String? = null,
    val user_roles: List<String> = emptyList(),
    val device_id: String,
    val device_type: String? = null,
    val device_os: String? = null,
    val device_os_version: String? = null,
    val device_manufacturer: String? = null,
    val device_model: String? = null,
    val device_screen_width: Int? = null,
    val device_screen_height: Int? = null,
    val device_locale: String? = null,
    val device_orientation: String? = null,
    val network_type: String? = null,
    val battery_level: Int? = null,
    val memory_free: Long? = null,
    val memory_total: Long? = null,
    val storage_free: Long? = null,
    val is_foreground: Int? = null,
    val is_rooted: Int? = null,
    val session_id: String,
    val session_start_time: Long? = null,
    val feature: String? = null,
    val screen_name: String? = null,
    val previous_screen: String? = null,
    val breadcrumb_type: String? = null,
    val duration_ms: Long? = null,
    val tags: List<String> = emptyList(),
    val feature_flags: String = "",
    val payload: String = "",
    val error_type: String? = null,
    val error_message: String? = null,
    val error_stacktrace: String? = null,
    val error_is_fatal: Int = 0,
    val error_thread: String? = null,
    val error_threads: String? = null,
)
